### ISSUE TITLE
still crashing every time I hit a tab and try to fill  :((

### ISSUE THREAD

**Issue by jorschneider** [luoliyan/chinese-support-redux#113]
**Describe the bug**

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.18 (fb9d59fe) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\browser.py", line 1067, in deferredDisplay
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-12>", line 2, in buildTree
  File "lib\site-packages\anki\hooks.py", line 82, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 74, in repl
  File "C:\Users\Jordan\AppData\Roaming\Anki2\addons21\1496166067\internals.py", line 218, in raw_new
    return wrapper(cls.instance, *args, **kwargs)
  File "C:\Users\Jordan\AppData\Roaming\Anki2\addons21\1496166067\stylers.py", line 362, in buildTree
    for item in root.findItems('', Qt.MatchContains | Qt.MatchRecursive):
AttributeError: 'SidebarTreeView' object has no attribute 'findItems'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]
 - Anki Version [e.g. v2.0.52, v2.1.5]
- Chinese Support Version [e.g. v0.5.3-beta]

windows
anki version Anki 2.1.18
china support version v0130

**Additional context**

**Comment by luoliyan** [comment]
Looks like an API change on Anki's end.

Consider it added to the growing to-do list.
