### ISSUE TITLE
extraneous error when loading backup

### ISSUE THREAD

**Issue by khonkhortisan** [luoliyan/chinese-support-redux#125]
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://help.ankiweb.net/discussions/add-ons/). 
Información de depuración: 
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-05-06 05:01:03

Caught exception:
Traceback (most recent call last):
  File "aqt\utils.py", line 366, in accept
  File "aqt\main.py", line 312, in doOpen
  File "aqt\main.py", line 345, in _openBackup
  File "aqt\main.py", line 253, in onOpenProfile
  File "aqt\main.py", line 398, in loadProfile
  File "aqt\gui_hooks.py", line 1559, in __call__
  File "lib\site-packages\anki\hooks.py", line 583, in runHook
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1128979221\main.py", line 60, in add_models
    if not mw.col.models.byName('Chinese (Advanced)'):
AttributeError: 'NoneType' object has no attribute 'models'
```

**Comment by jay-pee** [comment]
Can you give some steps how to reproduce this error?
