### ISSUE TITLE
incompatibility with review heatmap

### ISSUE THREAD

**Issue by khonkhortisan** [luoliyan/chinese-support-redux#126]
**Describe the bug**
`AttributeError: 'Finder' object has no attribute 'search'` when review heatmap 4e64a2f is enabled

**To Reproduce**
I'm using Anki 2.1.25
If using a version later than 2.1.19, modify templates/chinese.py using either https://github.com/luoliyan/chinese-support-redux/pull/117 or https://github.com/luoliyan/chinese-support-redux/pull/120 (I tried both)
enable review heatmap
add a model. note:ChinaProvinces fields:Map Name Chinese Traditional Pinyin Sound Capital Etymology Color ColorPY ColorBPMF
Chinese→Bulk Fill→Transcription

**Specs (please complete the following information):**
**Additional context**
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://help.ankiweb.net/discussions/add-ons/). 
Información de depuración: 
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-06 05:01:03

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1128979221\fill.py", line 156, in bulk_fill_transcript
    note_ids = Finder(mw.col).findNotes('deck:current')
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-58>", line 2, in __init__
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 630, in repl
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 149, in addFinders
    self.search["seen"] = self.findSeenOn
AttributeError: 'Finder' object has no attribute 'search'
```
If I disable review heatmap, chinese support starts processing cards instead

**Comment by khonkhortisan** [comment]
was my fault for using an old version, switched to review-heatmap-v1.0.0-beta.1-anki21.ankiaddon and it worked
