### ISSUE TITLE
error clicking in field

### ISSUE THREAD

**Issue by khonkhortisan** [luoliyan/chinese-support-redux#128]
I added the prefix CSR to all the fields it's allowed to change, added CSR to the minimum amount of fields in the note type it would need: CSRChinese CSRColor CSRColorPY CSRColorBPMF, clicked the button to add the model so there's a black underline, clicked in CSRChinese, and I get this error
![imagen](https://user-images.githubusercontent.com/1996449/81276698-3ade3280-9008-11ea-86fd-6919aa2867ac.png)

```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://help.ankiweb.net/discussions/add-ons/). 
Información de depuración: 
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-06 05:01:03

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\editor.py", line 393, in onBridgeCmd
  File "aqt\gui_hooks.py", line 1202, in __call__
  File "lib\site-packages\anki\hooks.py", line 594, in runFilter
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1128979221\edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 248, in update_fields
    hanzi = cleanup(get_first(config['fields']['hanzi'], copy))
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1128979221\util.py", line 69, in cleanup
    raise ValueError(text)
ValueError: None
```

**Comment by jay-pee** [comment]
When you change the names of the fields you have to adjust the settings of CSR. Go to Tools>Add-ons. Then select CSR and click on config. Here you can add your specific names.

**Comment by luoliyan** [comment]
I'm going to close this in favour of #127, and we'll just treat this as one big "config manager is broken" issue.
