### ISSUE TITLE
There seems to be a problem with Amazon Polly TTS -- No AWS credentials given

### ISSUE THREAD

**Issue by karma-works** [luoliyan/chinese-support-redux#143]
With Amazon Polly configured under Chinese --> Speech Engine I receive following error when I try to add new cards
----
Should this even work out of the box? Or am I missing something? Is there a possiblity to provide amazon credentials / Api Key? 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-14 18:09:14

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 31, in cmd
  File "aqt\webview.py", line 97, in _onCmd
  File "aqt\webview.py", line 500, in _onBridgeCmd
  File "aqt\editor.py", line 363, in onBridgeCmd
  File "aqt\gui_hooks.py", line 1006, in __call__
  File "lib\site-packages\anki\hooks.py", line 622, in runFilter
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 270, in update_fields
    fill_sound(hanzi, copy)
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 50, in download
    self.func()
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 87, in get_aws
    response = requests.post(url, json=query, auth=signer)
  File "lib\site-packages\requests\api.py", line 116, in post
  File "lib\site-packages\requests\api.py", line 60, in request
  File "lib\site-packages\requests\sessions.py", line 519, in request
  File "lib\site-packages\requests\sessions.py", line 452, in prepare_request
  File "lib\site-packages\requests\models.py", line 317, in prepare
  File "lib\site-packages\requests\models.py", line 548, in prepare_auth
  File "C:\Users\Christian\AppData\Roaming\Anki2\addons21\1128979221\aws.py", line 155, in __call__
    raise ValueError('No AWS credentials given')
ValueError: No AWS credentials given

**Comment by FaVorith** [comment]
Hi Christian,

You will need to provide credentials for AWS, as described here: https://github.com/luoliyan/chinese-support-redux/pull/92

In your case, the file needs to be placed under:
C:\Users\Christian\.aws\credentials

In the file "credentials" you need to paste your AWS API creds in the following format:
```
[default]
aws_access_key_id=*yourAccessKeyHere*
aws_secret_access_key=*YourSecretKeyHere*
```
Optionally you can also add "region=*regionName", by default Oregon (us-west-2) will be used.

Please note that if you create the file in Notepad, it will automatically add ".txt" to the name, i.e. your file will be "credentials.txt". In this case, you will have to manually remove the ".txt" extension.

Since keeping access keys in a plaintext file is not a best practice, I strongly encourage you to create a dedicated user for polling:
![image](https://user-images.githubusercontent.com/40296536/98365993-8f07b500-2033-11eb-9a8d-69899259d518.png)

Cheers,
Fabian

**Comment by karma-works** [comment]
It works like a glance with the API Key in the right place ( folder under windows is in my case C:\Users\Christian\.aws\credentials ). I wouldn't have arrived there without your description. Thanks a lot! 

I'm really appreciating this plugin, it's so useful! Keep up with the great work!
