### ISSUE TITLE
Chinese Support Redux v0140  don't work from 1 week

### ISSUE THREAD

**Issue by Perceval12** [luoliyan/chinese-support-redux#164]
For a week, the addon has not worked well.
After adding an info, the second crashes the program.

Information de débogage :
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-15 08:43:57

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "aqt\editor.py", line 403, in onBridgeCmd
  File "aqt\gui_hooks.py", line 1487, in __call__
  File "anki\hooks.py", line 594, in runFilter
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 270, in update_fields
    fill_sound(hanzi, copy)
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 50, in download
    self.func()
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 56, in get_google
    tts.save(self.path)
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts\tts.py", line 243, in save
    self.write_to_fp(f)
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts\tts.py", line 183, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts_token\gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "C:\Users\EasyWeb\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts_token\gtts_token.py", line 58, in _get_token_key
    raise ValueError(
ValueError: Unable to find token seed! Did https://translate.google.com change?

**Comment by JClouden12** [comment]
I'm having the same issue I think....

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-22 22:32:52
Add-ons possibly involved: ⁨Chinese Support Redux v0140⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "aqt/editor.py", line 403, in onBridgeCmd
  File "aqt/gui_hooks.py", line 1487, in __call__
  File "anki/hooks.py", line 594, in runFilter
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 270, in update_fields
    fill_sound(hanzi, copy)
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 50, in download
    self.func()
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 56, in get_google
    tts.save(self.path)
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 243, in save
    self.write_to_fp(f)
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 183, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/lib/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/Users/username/Library/Application Support/Anki2/addons21/1128979221/lib/gtts_token/gtts_token.py", line 58, in _get_token_key
    raise ValueError(
ValueError: Unable to find token seed! Did https://translate.google.com change?

**Comment by Jojo-23-23** [comment]
Hi,
I've also a bug when I clik on "Color".
Thanks

Erreur
￼ Une erreur est survenue. Veuillez démarrer Anki en maintenant la touche majuscule enfoncée, ce qui désactivera temporairement les greffons que vous avez installés. ￼ Si le problème ne survient que lorsque les greffons sont activés, veuillez utiliser le menu Outils > Greffons afin de désactiver certains greffons. Redémarrez Anki jusqu’à ce que vous découvriez le greffon qui cause le problème. ￼ Une fois ce greffon découvert, merci de signaler le problème sur le site de support du greffon.￼ ￼ Information de débogage :
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-23 09:34:57

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\editor.py", line 393, in onBridgeCmd
  File "aqt\gui_hooks.py", line 1202, in __call__
  File "lib\site-packages\anki\hooks.py", line 594, in runFilter
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 270, in update_fields
    fill_sound(hanzi, copy)
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 50, in download
    self.func()
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 56, in get_google
    tts.save(self.path)
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts\tts.py", line 243, in save
    self.write_to_fp(f)
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts\tts.py", line 183, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts_token\gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "C:\Users\jojoi\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts_token\gtts_token.py", line 58, in _get_token_key
    raise ValueError(
ValueError: Unable to find token seed! Did https://translate.google.com change?

**Comment by luoliyan** [comment]
Should be fixed in the newest version. Try again tomorrow and reopen the ticket if there's still a problem.

**Comment by Jojo-23-23** [comment]
Hi. Thank you very much.
I've installed the new version and tested.
Now, the fields are populated automatically. It's genius.
But there are 2 small problems.
1. The color doesn't appear. The fields Color and Pinyin are only in black color.
2. The field Sound is filled, but doesn't work. May be I have to do something, but, what should I do ?

Thanks a lot for your help.
Perfect, I'm happy.

**Comment by luoliyan** [comment]
The 2nd issue should be fixed in v0.14.2 which I uploaded earlier today. If it's not, let me know.

The colour issue isn't one I've seen, but I'll investigate tonight.

**Comment by luoliyan** [comment]
I've just tested on a fresh install of Anki ⁨2.1.43 with CSR 0.14.2, and the fields are populated and sound is generated. Not sure why it isn't working in your case.

**Comment by Jojo-23-23** [comment]
Hi, thanks,
I've installed the new versions. It's better.
The pinyin and hanzi are good but without the colors.
See you. Great

**Comment by luoliyan** [comment]
I think the colour still shows up while reviewing, just not when you're
creating the card, right?

**Comment by Jojo-23-23** [comment]
Hi. The color doesn't appear. Neither creating the card, neither reviewing.
Thanks
