### ISSUE TITLE
Bulk Fill Error

### ISSUE THREAD

**Issue by dynnamic** [luoliyan/chinese-support-redux#177]
Can't seem to get Bulk Fill to work.

Bulk Fill>> All gives me the follow error

> Traceback (most recent call last):
>   File "/Users/xxxx/Library/Application Support/Anki2/addons21/1128979221/fill.py", line 96, in bulk_fill_all
>     'hanzi': get_hanzi(dict(note)),
>   File "/Users/xxxx/Library/Application Support/Anki2/addons21/1128979221/hanzi.py", line 52, in get_hanzi
>     return cleanup(get_first(config['fields']['hanzi'], note))
>   File "/Users/xxxx/Library/Application Support/Anki2/addons21/1128979221/util.py", line 69, in cleanup
>     raise ValueError(text)
> ValueError: None

Could this be related to the fact that many of the cards have formatting from the previous rendition of the Chinese Support Addon?

Thanks

**Comment by luoliyan** [comment]
I'm fairly confident I have this fixed in the current version, which will go up on AnkiWeb later today.

I'll leave this open in case you still have issues.

**Comment by fultonm** [comment]
Just took the update this afternoon. Getting the following Error with bulk fill sound on Google Mandarin PRC. Baidu works fine

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-26 14:11:49

Caught exception:
Traceback (most recent call last):
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\fill.py", line 154, in bulk_fill_sound
    s, f = fill_sound(hanzi, copy)
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\sound.py", line 51, in sound
    return '[sound:%s]' % AudioDownloader(hanzi, source).download()
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 50, in download
    self.func()
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\tts.py", line 56, in get_google
    tts.save(self.path)
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts\tts.py", line 321, in save
    self.write_to_fp(f)
  File "C:\Users\m\AppData\Roaming\Anki2\addons21\1128979221\lib\gtts\tts.py", line 303, in write_to_fp
    raise gTTSError(tts=self, response=r)
gtts.tts.gTTSError: 200 (OK) from TTS API. Probable cause: Unknown

**Comment by joeminicucci** [comment]
@dynnamic Can you confirm if you are still experiencing issues?

**Comment by spolcyn** [comment]
@joeminicucci I can confirm that I'm still experiencing this issue with Anki 2.1.44 and CSR v0142

**Comment by spolcyn** [comment]
@joeminicucci Added a PR that should fix this for `usage`
