### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by telotortium** [luoliyan/chinese-support-redux#20]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.6-test Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Mac 10.14.1
Flags: frz=True ao=True sv=1

--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\uff1f' in position 145: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 262, in run
  File "aqt/__init__.py", line 347, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 346, in _onBridgeCmd
  File "aqt/editor.py", line 268, in onBridgeCmd
  File "anki/hooks.py", line 34, in runFilter
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 61, in onFocusLost
    if updateFields(note, field, allFields):
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 469, in updateFields
    update_all_Sound_fields(fieldsCopy[currentField], fieldsCopy)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 350, in update_all_Sound_fields
    updated1, errors1 = update_Sound_fields(hanzi, dico)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 315, in update_Sound_fields
    s = sound(hanzi)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_functions.py", line 410, in sound
    return '[sound:%s]' % tts.download_sound(text, options[source])
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 34, in download_sound
    tts = gTTS(text, lang=lang)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 108, in __init__
    log.debug("%s: %s", k, v)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 66-68: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 262, in run
  File "aqt/__init__.py", line 347, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 346, in _onBridgeCmd
  File "aqt/editor.py", line 268, in onBridgeCmd
  File "anki/hooks.py", line 34, in runFilter
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 61, in onFocusLost
    if updateFields(note, field, allFields):
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 469, in updateFields
    update_all_Sound_fields(fieldsCopy[currentField], fieldsCopy)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 350, in update_all_Sound_fields
    updated1, errors1 = update_Sound_fields(hanzi, dico)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 315, in update_Sound_fields
    s = sound(hanzi)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_functions.py", line 410, in sound
    return '[sound:%s]' % tts.download_sound(text, options[source])
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 34, in download_sound
    tts = gTTS(text, lang=lang)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 108, in __init__
    log.debug("%s: %s", k, v)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 96-98: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 262, in run
  File "aqt/__init__.py", line 347, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 346, in _onBridgeCmd
  File "aqt/editor.py", line 268, in onBridgeCmd
  File "anki/hooks.py", line 34, in runFilter
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 61, in onFocusLost
    if updateFields(note, field, allFields):
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 469, in updateFields
    update_all_Sound_fields(fieldsCopy[currentField], fieldsCopy)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 350, in update_all_Sound_fields
    updated1, errors1 = update_Sound_fields(hanzi, dico)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 315, in update_Sound_fields
    s = sound(hanzi)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_functions.py", line 410, in sound
    return '[sound:%s]' % tts.download_sound(text, options[source])
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 35, in download_sound
    tts.save(path)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 204, in write_to_fp
    log.debug("payload-%i: %s", idx, payload)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 177-179: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 262, in run
  File "aqt/__init__.py", line 347, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 346, in _onBridgeCmd
  File "aqt/editor.py", line 268, in onBridgeCmd
  File "anki/hooks.py", line 34, in runFilter
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 61, in onFocusLost
    if updateFields(note, field, allFields):
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 469, in updateFields
    update_all_Sound_fields(fieldsCopy[currentField], fieldsCopy)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 350, in update_all_Sound_fields
    updated1, errors1 = update_Sound_fields(hanzi, dico)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 315, in update_Sound_fields
    s = sound(hanzi)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_functions.py", line 410, in sound
    return '[sound:%s]' % tts.download_sound(text, options[source])
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 35, in download_sound
    tts.save(path)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 230, in write_to_fp
    log.debug("part-%i written to %s", idx, fp)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 135-137: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 262, in run
  File "aqt/__init__.py", line 347, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 85, in _onCmd
  File "aqt/webview.py", line 346, in _onBridgeCmd
  File "aqt/editor.py", line 268, in onBridgeCmd
  File "anki/hooks.py", line 34, in runFilter
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 61, in onFocusLost
    if updateFields(note, field, allFields):
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 469, in updateFields
    update_all_Sound_fields(fieldsCopy[currentField], fieldsCopy)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 350, in update_all_Sound_fields
    updated1, errors1 = update_Sound_fields(hanzi, dico)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_behavior.py", line 315, in update_Sound_fields
    s = sound(hanzi)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/edit_functions.py", line 410, in sound
    return '[sound:%s]' % tts.download_sound(text, options[source])
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 35, in download_sound
    tts.save(path)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1128979221/lib/gTTS/gtts/tts.py", line 248, in save
    log.debug("Saved to %s", savefile)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.

**Comment by luoliyan** [comment]
Thanks. What was in the Hanzi field when this error occurred. I assume you were adding a new note when this happened?

**Comment by telotortium** [comment]
Yes, I was entering a new note. I was entering "加拿大" (without quotes).

**Comment by telotortium** [comment]
Still happening to me on v100. I sent #55 which seems to fix it.
