### ISSUE TITLE
KeyError exception when autofilling

### ISSUE THREAD

**Issue by jorschneider** [luoliyan/chinese-support-redux#83]
When I hit tab it doesn't fill out anything but just dies ;((

I've tried disabling sound as well as updating anki to 2.14 (it was also crashing with 2.13). 

here's the error message:
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.5
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Chinese Support Redux v0111

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/editor.py", line 273, in onBridgeCmd
  File "anki/hooks.py", line 39, in runFilter
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 308, in update_fields
    fill_color(hanzi, copy)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 203, in fill_color
    set_all(config['fields']['colorHanzi'], note, to=colorized)
<class 'KeyError'>: 'colorHanzi'

**Expected behavior**

**Screenshots**

**Specs (please complete the following information):**
 - OS: mac
 - Anki Version 2.14
- Chinese Support Version v0111

**Comment by jorschneider** [comment]
was all going fine until two days ago when this started happening. Have tried restarting to no avail.

Thanks for all the work you put in to this by the way this app has seriously changed my life!

**Comment by luoliyan** [comment]
Sorry that I broke it for you.

Could you post the contents of `/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/meta.json` here (or email it to me), then delete it from that folder.

**Comment by jorschneider** [comment]
thanks!

{"name": "Chinese Support Redux v0111", "mod": 1565003018, "config": {"firstRun": false, "version": "0.11.1", "enabledModels": ["1377171239634"], "speech": null, "target": "pinyin", "fields": {"hanzi": ["Chinese", "Expression", "Hanzi", "\u4e2d\u6587", "\u6c49\u5b57", "\u6f22\u5b57"], "meaning": ["Definition", "Meaning", "\u610f\u601d", "\u7ffb\u8b6f", "\u7ffb\u8bd1", "\u89e3\u91ca", "\u89e3\u91cb"], "english": ["English", "\u82f1\u6587", "\u82f1\u8a9e", "\u82f1\u8bed"], "german": ["Deutsch", "German", "\u5fb7\u6587", "\u5fb7\u8a9e", "\u5fb7\u8bed"], "french": ["French", "le fran\u00e7ais", "\u6cd5\u6587", "\u6cd5\u8a9e", "\u6cd5\u8bed"], "transcription": ["Reading"], "pinyin": ["PY", "Pinyin", "\u5927\u9646\u62fc\u97f3", "\u5927\u9678\u62fc\u97f3", "\u62fc\u97f3"], "pinyinTaiwan": ["PYTW", "PinyinTW", "\u53f0\u6e7e\u62fc\u97f3", "\u53f0\u7063\u62fc\u97f3", "\u81fa\u7063\u62fc\u97f3"], "cantonese": ["Cantonese", "\u5e7f\u4e1c\u8bdd", "\u5e7f\u5dde\u8bdd", "\u5ee3\u5dde\u8a71", "\u5ee3\u6771\u8a71", "\u7ca4", "\u7ca4\u62fc", "\u7ca4\u8bed", "\u7cb5", "\u7cb5\u62fc", "\u7cb5\u8a9e"], "bopomofo": ["Bopomofo", "\u3105\u3106\u3107\u3108", "\u6ce8\u97f3\u7b26\u53f7", "\u6ce8\u97f3\u7b26\u865f", "\u8a3b\u97f3\u7b26\u865f"], "sound": ["Audio", "Sound", "Spoken", "\u58f0\u97f3", "\u8072\u97f3"], "mandarinSound": ["Sound - Mandarin"], "cantoneseSound": ["Sound - Cantonese"], "simplified": ["Simp", "Simp.", "Simplified", "\u7b80\u4f53", "\u7b80\u4f53\u5b57", "\u7b80\u5316", "\u7b80\u5316\u5b57", "\u7c21\u5316", "\u7c21\u5316\u5b57", "\u7c21\u9ad4", "\u7c21\u9ad4\u5b57"], "traditional": ["Trad", "Trad.", "Traditional", "\u7e41\u4f53", "\u7e41\u4f53\u5b57", "\u7e41\u9ad4", "\u7e41\u9ad4\u5b57"], "classifier": ["Classifier", "MW", "Mean Word", "Mean", "Measure Word", "\u91cf\u8a5e", "\u91cf\u8bcd"], "alternative": ["Also Written", "Alt", "Alternative"], "color": ["Color", "Colored Hanzi", "Colour", "Coloured Hanzi", "\u5f69\u8272"], "colorPinyin": ["ColorPY", "ColourPY"], "colorPinyinTaiwan": ["ColorPYTW", "ColourPYTW"], "colorCantonese": ["ColorCANT", "ColourCANT"], "colorBopomofo": ["ColorBPMF", "ColourBPMF"], "ruby": ["Ruby"], "rubyPinyin": ["RubyPY"], "rubyPinyinTaiwan": ["RubyPYTW"], "rubyCantonese": ["RubyCANT"], "rubyBopomofo": ["RubyBPMF"], "silhouette": ["Silhouette"]}, "dictionary": "en", "show_tips": false, "tip_number": 0, "transcription": "Pinyin"}}

**Comment by jorschneider** [comment]
then got this error

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.5
Flags: frz=True ao=True sv=1
Add-ons possibly involved: 1128979221

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/editor.py", line 273, in onBridgeCmd
  File "anki/hooks.py", line 39, in runFilter
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 308, in update_fields
    fill_color(hanzi, copy)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 203, in fill_color
    set_all(config['fields']['colorHanzi'], note, to=colorized)
<class 'KeyError'>: 'colorHanzi'

**Comment by DanGould** [comment]
I second this `<class 'KeyError'>: 'colorHanzi` issue running v0111 on Anki Version 2.1.12 (eef86bf3)
Qt 5.12.1 PyQt 5.11.3

**Comment by DanGould** [comment]
After re-installing, I notice if I select pinyin or pinyin (Taiwan) transcription then everything works as advertised. If I select bopomofo then I still get pinyin, and if I select Jyutping then I get this same KeyError error again. For the time being, I'll just use Pinyin.

Strange feeling bubbling that this is related to the ㄅㄆㄇㄈ transcription not separating phonetics for words with spaces and tones. I don't know about Jyutping.

**Comment by jorschneider** [comment]
ah even with pinyin (what i've been using) it still crashes

**Comment by luoliyan** [comment]
I'm hoping this is all fixed in v0.11.3 that was just uploaded to AnkiWeb.

Thanks for your patience. The way Anki handles configuration files is just frustrating and unintuitive. I've decided to ignore the built-in config functions and handle it manually, which will hopefully stop this from happening.

**Comment by DanGould** [comment]
I am not experiencing this crashing any longer in v0.11.5

**Comment by luoliyan** [comment]
Thank God.

**Comment by jorschneider** [comment]
so it works for me now but every time it still crashes! here's the error message

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.5
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Chinese Support Redux v0115

--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 96-109: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 276, in run
  File "aqt/__init__.py", line 363, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/editor.py", line 273, in onBridgeCmd
  File "anki/hooks.py", line 39, in runFilter
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 267, in update_fields
    fill_sound(hanzi, copy)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/sound.py", line 48, in sound
    return '[sound:%s]' % download(hanzi, source)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 37, in download
    tts.save(path)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 243, in save
    self.write_to_fp(f)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 200, in write_to_fp
    log.debug("payload-%i: %s", idx, payload)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 188-201: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 276, in run
  File "aqt/__init__.py", line 363, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/editor.py", line 273, in onBridgeCmd
  File "anki/hooks.py", line 39, in runFilter
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 267, in update_fields
    fill_sound(hanzi, copy)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/sound.py", line 48, in sound
    return '[sound:%s]' % download(hanzi, source)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 37, in download
    tts.save(path)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 243, in save
    self.write_to_fp(f)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 226, in write_to_fp
    log.debug("part-%i written to %s", idx, fp)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 996, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 146-159: ordinal not in range(128)
Call stack:
  File "runankimac", line 12, in <module>
  File "aqt/__init__.py", line 276, in run
  File "aqt/__init__.py", line 363, in _run
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/editor.py", line 273, in onBridgeCmd
  File "anki/hooks.py", line 39, in runFilter
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/edit.py", line 74, in onFocusLost
    if update_fields(note, field, allFields):
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 267, in update_fields
    fill_sound(hanzi, copy)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/behavior.py", line 169, in fill_sound
    s = sound(hanzi, config['speech'])
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/sound.py", line 48, in sound
    return '[sound:%s]' % download(hanzi, source)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/tts.py", line 37, in download
    tts.save(path)
  File "/Users/jordanschneider/Library/Application Support/Anki2/addons21/1128979221/lib/gtts/tts.py", line 244, in save
    log.debug("Saved to %s", savefile)
  File "logging/__init__.py", line 1296, in debug
  File "logging/__init__.py", line 1444, in _log
  File "logging/__init__.py", line 1454, in handle
  File "logging/__init__.py", line 1516, in callHandlers
  File "logging/__init__.py", line 865, in handle
  File "logging/__init__.py", line 1072, in emit
  File "logging/__init__.py", line 1000, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.

**Comment by jorschneider** [comment]
really appreciate you getting to this by the way!

**Comment by luoliyan** [comment]
Can you try deleting the `1128979221` folder and reinstalling the add-on. That backtrace makes no sense to me, since the error occurs inside gTTS.

What were you putting in the Hanzi field?

**Comment by jorschneider** [comment]
boom and we're all set! thanks again you guys are legends.

Is there a patreon/if not wanna pick a charity of your choice? Seriously I
owe so much to this add on...

**Comment by luoliyan** [comment]
Just pay it forward, I suppose.

Otherwise, GiveWell is doing good work.

**Comment by jorschneider** [comment]
[image: image.png]
